---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - config/telegram_config.yml

  tasks:

  - uri: url="https://api.telegram.org/{{ tokenBot }}/sendmessage?chat_id={{ chatID }}&parse_mode=HTML&text=You%20have%20new%20<b>pending%20approvals.</b>%20Check%20<a%20href="http://52.117.0.47">IBM%20Cloud%20Ansible%20Tower</a>"
