---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    service_main_config_file: "config/deleteAll_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Deleting document roots
    command: rm -rf "{{ item }}" 
    with_items: "{{ service_config_var_document_root }}"
    ignore_errors: yes

  - name: Deleting HTTP software service
    yum: name={{ item }} state=absent
    with_items: "{{ service_pkgs }}"

  - name: Deleting NGINX repo
    yum_repository:
       name: "{{ service_software_repo_name }}" 
       state: absent
